title: Home
email:
description: >-
  Adam Dennis - PhD researcher in Blast and Impact Engineering at the University of Sheffield.
github_username: adamdennis98
minimal_mistakes_skin: dark
repository: adamdennis98/adamdennis98.github.io
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages
  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Adam Dennis"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "PhD researcher in blast and impact engineering."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adamdennis98"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/adam-dennis-uos"
    - label: "ResearchGate"
      icon: "fa fa-graduation-cap"
      url: "https://www.researchgate.net/profile/Adam-Dennis"
    - label: "University"
      icon: "fa fa-university"
      url: "https://www.sheffield.ac.uk/civil/people/research/adam-dennis" 

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/adamdennis98"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/adam-dennis-uos"
    - label: "ResearchGate"
      icon: "fa fa-graduation-cap"
      url: "https://www.researchgate.net/profile/Adam-Dennis"
    - label: "University"
      icon: "fa fa-university"
      url: "https://www.sheffield.ac.uk/civil/people/research/adam-dennis" 

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single  
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false
      
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: false
      share: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
